name: Build Windows Executable

# 触发条件
on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    # 1. 检出代码
    - name: Checkout code
      uses: actions/checkout@v4
    
    # 2. 设置Python环境
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    # 3. 缓存依赖（加速构建）
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    # 4. 安装依赖
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller
    
    # 5. 构建可执行文件
    - name: Build executable
      run: |
        pyinstaller --onefile --windowed --name "ImageProcessor" main.py
        # 或者使用spec文件：pyinstaller app.spec
    
    # 6. 测试可执行文件（可选）
    - name: Test executable
      run: |
        dir dist
        # 可以添加简单的测试命令
    
    # 7. 上传构建产物
    - name: Upload executable
      uses: actions/upload-artifact@v3
      with:
        name: windows-executable-${{ github.sha }}
        path: dist/ImageProcessor.exe
        retention-days: 30
    
    # 8. 创建Release（仅在推送tag时）
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/ImageProcessor.exe
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}